### ISSUE TITLE
Living spectator bug

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#245]
Often, after loading a new map, there's a chance a round starts with a 'living' spectator, and nothing can be done unless i slay all living players or force the round to end. Particularly problematic if the first round starts as a boss round.

**Comment by 50Wliu** [comment]
Not fixed.

**Comment by WildCard65** [comment]
I think the issue might be that their being moved to teams too fast for the game to register them as dead. I think they may also have a class of TFClass_Unknown(0). I think a plausible fix is to in OnGameFrame check for living spectators and if one is detected, force a stalemate, increase mp_maxrounds by 1(to compensate for loss round), if it's a normal arena round, kick it into ff2, otherwise, don't subtract queue points of last hale, give them boss they were last, and restart from there.

**Comment by shadow93** [comment]
Here's the interesting thing, when you do a GetPlayerClass and a GetClientTeam check, it reports back as the correct class and team, despite being a living spectator.
```sourcepawn
[FF2] ★[SHADoW] 古明地 こいし became SoupCock Porkpie with 3000 hp!
[FF2 DEBUG] Client ★[SHADoW] 古明地 こいし is TFClass: 4 on TFTeam: 3
[FF2 DEBUG] Client It's Filthy in There! is TFClass: 1 on TFTeam: 2
```

**Comment by WildCard65** [comment]
There goes my theory then. PLAN B! Find the matching player entity in world?

**Comment by shadow93** [comment]
```sourcepawn
 [FF2 DEBUG] Client ★[SHADoW] 古明地 こいし | TFClass: 5 | TFTeam: 2 | IsPlayerAlive: 1 | UserID: 20 | OfUserId: 0 | Ent: 1
[FF2 DEBUG] Client NotMe | TFClass: 3 | TFTeam: 3 | IsPlayerAlive: 1 | UserID: 54 | OfUserId: 0 | Ent: 2
```

**Comment by shadow93** [comment]
Seems to have resurfaced again.

On another note, this might be able to help us to check if a living player is TRULY a living spectator:
```sourcepawn
GetEntProp(client, Prop_Send, "m_iObserverMode");
```

**Comment by 50Wliu** [comment]
This has been fixed by the linked PR.

**Comment by 50Wliu** [comment]
Guess what, still not fixed.

**Comment by 50Wliu** [comment]
Also, for your stock, I'm guessing that a value of 3 means that you're spectating the map.

**Comment by shadow93** [comment]
Updated the stock with the one i use in my FF2.
