### ISSUE TITLE
Problem who's fix just made worse

### ISSUE THREAD

**Issue by WildCard65** [50DKP/FF2-Official#261]
https://github.com/50DKP/FF2-Official/commit/71e34c1d65ac875e9e030f1745b13d5e5c80e0d2 just made a minor problem much more worse by introducing a constant 0 to when ever it occurs. That and it has a redundant way of detecting left over operator.

**Comment by WildCard65** [comment]
I'll leave an example of how things will explode with forcing 0 on lingering operators.
(760*n)*)/2 = 0/2 = 0

**Comment by shadow93** [comment]
.....

**Comment by 50Wliu** [comment]
> Before commit, it would end up like this: (760*n)/2

No it wouldn't.  What would actually happen is it would become n/2.
Here's my reasoning:
* Bracket becomes 1 upon reaching `(`
* 7, 6, and 0 are appended to `value` making it 760
* `n` is operated on using `Operator_None`
* `Operate()` sets bracket 1's value to `n` because of `Operator_None`, *completely ignoring 760*
* Bracket becomes 0 upon reaching `)`
* Divide by 2

Correct me if I'm wrong.

**Comment by WildCard65** [comment]
@50Wliu What you described is 100% impossible.
This is what suppose to happen:
* bracket = 1
* 7, 6, 0 is appended onto value making it read 760
* Parser comes to * forcing it to call OperateString while _operator is Operator_None forcing Operate to just set sumArray at 1 to 760.0. Then it stores the * as the operator.
* n is parsed and calls Operate with playing, it uses the * operator on 760.
* ) is reached and atm _operator 0 is Operator_None so value of 760*n is set to sumArray at 0.
* Parser comes to / and calls OperateString and it's blank string blocker prevents Operate from replacing 760+n with 0.
* 2 is parsed and end of string is reached and Operate divides 760*n by 2

**Comment by 50Wliu** [comment]
Fixed by https://github.com/50DKP/FF2-Official/commit/7ae9c26b77fe0bfbc19873fc23bb6a8f1561166a.
