### ISSUE TITLE
Backstabs penetrating through all lives when HP <= 2K

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#273]
The "[bossname] lost a life [lives] lives remain!" hud text still pop up as normal, but the backstab damage penetrates through ALL the boss's lives, making backstabs a one-hit kill.

Shortly after that, this is how /ff2hp reports the affected boss's HP:
![2015-07-09_00005](https://cloud.githubusercontent.com/assets/9245131/8611768/0c4dba40-2694-11e5-9731-01f5d9ad0247.jpg)

**Comment by Deathreus** [comment]
This sounds to be due to how poorly lives was actually handled, it calculates lives as the full health, and reads the lives based on health left, a backstab will hit for the full health he normally would have, and this radical change in life is misread in the lives and actually kills him before the lives can respond

**Comment by 50Wliu** [comment]
...and once again my extra commit info didn't go through.

**Comment by 50Wliu** [comment]
Never mind, not fixed.

**Comment by 50Wliu** [comment]
So TF2 is being annoying somewhere.
