### ISSUE TITLE
Override ALL Mediguns?

### ISSUE THREAD

**Issue by shadow93** [50DKP/FF2-Official#329]
Since VSH now overrides attributes for all mediguns, why don't we do the same so the Kritzkrieg, Quick Fix and Vaccinator are treated as another Medigun reskin (overriding it's attributes)?

**Comment by naydef** [comment]
I also have the same idea. It is also better to override all Syringe gun attributes instead of replacing them. There are many positive things like no more invisible mediguns and syringeguns. Also I can confirm the bug, where if the ubercharge goes below 40% the healer will lost his uber protection, maybe because the ubercharge is now hardcoded to 100%.

**Comment by shadow93** [comment]
The uber bug is also confirmed in my version too.

**Comment by 50Wliu** [comment]
Sounds good.

The ubercharge is a TF2 bug which I will not be fixing within FF2.

**Comment by shadow93** [comment]
I guess we can close this since the PR is merged
