### ISSUE TITLE
FF2 "block" some attributes?

### ISSUE THREAD

**Issue by tigocesar** [50DKP/FF2-Official#363]
Hi
i'm using version: 1.10.8
On my server , I change some attributes with tf2items . Some, like for my administrators i put Australium weapons. In the first round , when freak doesn't work for expecting some load people, Australium work very well. But when " Start" the freak mod , these weapons don't work anymore , they turn to the "quality" standard ( stock ) . And when I try to do this on my other server ( 4ver turbine) this weapon works like a charm . I wonder if freak "locks" certain attributes of weapons and if you can solve it for me on a version 1.10.9

**Comment by Deathreus** [comment]
Depending on the weapons, FF2 rewrites attributes on the weapon to balance it, most stock weapons get change, but I believe there's a couple that remain untouched

**Comment by 50Wliu** [comment]
@Deathreus is correct.  For many weapons the attributes are completely wiped, but for others they're added onto the existing ones.  You will have to edit the FF2 source yourself in order to customize the weapon attributes (sorry!  That'll be improved in v2).  Most of the attributes are set in `TF2Items_OnGiveNamedItem`.
