### ISSUE TITLE
Sound_Kill playing while Sound_win is playing at the same time

### ISSUE THREAD

**Issue by WakaFloockaFlame** [50DKP/FF2-Official#364]
Sound_kill_(classname) plays the same time as sound_win same goes for sound_hit and wiiu don't start saying bullshit like its only on your server since it doesn't occur on the test server or anyone else's servers. you say that for every issue i report and it's getting annoying so cut it out. It's obviously a FF2 issue so you and the FF2 team please consider fixing it thanks

**Comment by shadow93** [comment]
You can just work around this by making a 0.1 second timer that fires, and if CheckRoundState()!=1, return Plugin_Stop.

**Comment by 50Wliu** [comment]
> wiiu don't start saying bullshit like its only on your server since it doesn't occur on the test server or anyone else's servers. you say that for every issue i report and it's getting annoying so cut it out.

I keep saying it because it's true, so no, I won't cut it out.  I just tried (again) five times in a row with sounds set to always play instead of a 1/2 + 1/3 chance, and still cannot reproduce.  The test server is open to everyone and the IP address is located on the main FF2 thread.  The least you could do is try to reproduce your bug on there first.

(Tried using commit 6138537474d173cd76b08c23db7c491aec3f8221)

**Comment by Deathreus** [comment]
This bug was fixed a looooong time ago, and it actually didn't happen consistently for me on my server, it just occasionally played both, but it hasn't done such a thing since it was fixed
