### ISSUE TITLE
Still have a problem "My server still says the game is "Team Fortress" instead of "Freak Fortress 2""

### ISSUE THREAD

**Issue by DartCrusaderBn** [50DKP/FF2-Official#529]
Still have a problem "My server still says the game is "Team Fortress" instead of "Freak Fortress 2""
and it's still named Team fortress AFTER installing SteamTools

**Comment by chocochocotorta** [comment]
I think you need this:
https://forums.alliedmods.net/showthread.php?p=1583349

**Comment by MAGNAT2645** [comment]
I have same problem but i use [SteamWorks](https://forums.alliedmods.net/showthread.php?t=229556) and [SW GameDesc Override](https://forums.alliedmods.net/showthread.php?t=252712) (used `sw_gamedesc_override` but description doesn't change). I think it might be a bug that needs to be fixed in extension itself (SteamTools or SteamWorks).
